name: Build Container Image

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.head_ref }}
  cancel-in-progress: true

env:
  image: ghcr.io/${{ github.repository }} # ghcr.io/<owner>/<repo>
  registry_user: ${{ github.actor }}
  registry_token: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Configure Docker Build Cache
      id: cache
      uses: int128/docker-build-cache-config-action@v1
      with:
        image: ${{ env.image }}
        flavor: prefix=buildcache-

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.image }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=sha

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.image }}
        username: ${{ env.registry_user }}
        password: ${{ env.registry_token }}

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: "{{defaultContext}}:."
        file: ./Dockerfile
        provenance: false
        sbom: false
        cache-from: ${{ steps.cache.outputs.cache-from }}
        cache-to: ${{ steps.cache.outputs.cache-to }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
